name: Invitation to the 64 Shades GitHub Community Organization
description: I would like to be part of the 64 Shades World Chess Team
title: Please invite me to the 64 Shades GitHub Community Organization
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
